services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: demoapp1
    container_name: demodc1
    ports:
      - "8080:8080"
      - "8081:8081"
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__Demo=Server=host.docker.internal,1433;Database=DemoAPI;User Id=sa;Password=123456;TrustServerCertificate=True;MultipleActiveResultSets=True
    networks:
    - my_network


networks:
  my_network:
    driver: bridge